### ISSUE TITLE
Getting started additional steps

### ISSUE THREAD

**Issue by MaerF0x0** [volatiletech/abcweb#10]
I had to do some additional stuff to start a new projects (on macosx)

```
brew install postgresql
brew services start postgresql
createuser -P myapp
createdb myapp
```

**Comment by nullbio** [comment]
Hi @MaerF0x0. Because users have a choice of their database (could be MySQL, MariaDB, Postgres, and maybe more in the future) and each of these have their own unique installation procedures for every different operating system (Windows, MacOSX, Linux, etc), it would be difficult to cover this in the readme. This is also documentation that isn't being maintained by the people in charge of producing these installation mechanisms, and so if something were to change it wouldn't be reflected in the readme. That's why I've opted not to have database installation instructions included in the readme and it's left as an exercise to the user.
