### ISSUE TITLE
Not using HTTP2

### ISSUE THREAD

**Issue by MaerF0x0** [volatiletech/abcweb#11]
As far as I can tell its not using HTTP2 (in dev, at least)? 

i used "HTTP/2 and SPDY indicator"  for chrome and tried hitting  `myapp:4000`. Indicates it's not using http2.  sites like facebook.com or google.com indicate positively.

**Comment by nullbio** [comment]
The only way HTTP2 is possible in Go is if you combine it with SSL, so unless you're using SSL for dev mode (which you won't be by default due to the configuration file that is generated) it won't be using HTTP2. You can enable SSL using the generated SSL certificates in your app directory. The annoying part about this will be that most browser will require you to add an exception manually since these aren't signed by a trusted root authority.
