### ISSUE TITLE
`abcweb dev` pinning a core

### ISSUE THREAD

**Issue by MaerF0x0** [volatiletech/abcweb#12]
Any way we can make it so it doesnt pin a core? Will chew through a laptop battery in no time, meaning I cant dev in a coffee shop or something.  
A couple screenshots from activity monitor CPU and Energy tabs.

<img width="797" alt="screen shot 2017-07-04 at 7 34 04 am" src="https://user-images.githubusercontent.com/247846/27834341-6feefdb0-608b-11e7-9b22-99a6552b19ea.png">
<img width="798" alt="screen shot 2017-07-04 at 7 35 06 am" src="https://user-images.githubusercontent.com/247846/27834342-6fef2ad8-608b-11e7-8db5-417ce3b95131.png">

Aside: I know I've opened many issues, let me know which you'd like me to tackle.

**Comment by nullbio** [comment]
Interesting. Is this only when saving files or at all times? I'll have to look into this one further. If it's when you're saving files I would imagine it is due to gulps execution, which would be out of our control. If it's continuous then this may be something that can be fixed, I'd have to see. It also might be unique to OSX as well, which I've never tested on (I'm using Ubuntu).

**Comment by nullbio** [comment]
I believe this was due to the refresh library, and the problem has now been fixed in v3: https://github.com/volatiletech/abcweb/releases/tag/v3.0.0 -- please let me know if any problems persist, thank you.
